# Generated by Django 3.2.6 on 2021-09-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banner.place'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='place_image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_images', to='banner.place'),
        ),
    ]
