# Generated by Django 3.2.6 on 2021-09-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20210909_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='post',
            new_name='tadbirkor',
        ),
    ]
