# Generated by Django 3.2.6 on 2021-09-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_rename_post_order_tadbirkor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
    ]
