# Generated by Django 3.2.6 on 2021-10-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_delete_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='banner.place'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tadbirkor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='banner.tadbirkor'),
        ),
    ]
