# Generated by Django 3.2.6 on 2021-11-06 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_auto_20211030_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.ForeignKey(limit_choices_to={'busy': "Bo'sh"}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='banner.place'),
        ),
    ]
